# Generated by Django 2.2.dev20180612192205 on 2018-06-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_list', '0004_auto_20180616_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created']},
        ),
    ]
