# Generated by Django 2.2.dev20180612192205 on 2018-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_list', '0005_auto_20180616_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
