# Generated by Django 2.2.dev20180612192205 on 2018-06-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_list', '0008_auto_20180617_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
