# Generated by Django 2.2.dev20180612192205 on 2018-06-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_list', '0013_auto_20180617_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to='users_avatars'),
        ),
    ]
