# Generated by Django 2.2.dev20180612192205 on 2018-06-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_list', '0016_auto_20180618_0010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to='users_avatars'),
        ),
    ]
