# Generated by Django 2.2.dev20180612192205 on 2018-06-18 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_list', '0018_auto_20180618_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ask_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
