# Generated by Django 2.2.dev20180612192205 on 2018-06-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_list', '0019_auto_20180618_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='question_list.Tag'),
        ),
    ]
